site_name: Roseau
site_url: https://alien-tools.github.io/roseau
site_description: Roseau checks breaking changes and binary or source compatibility between two versions of a Java library.

theme:
  name: material

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - CLI Options: reference/cli.md
  - Guides:
      - Check Breaking Changes: guides/compare.md
      - Use in CI: guides/ci.md
      - Ignore Accepted Breaking Changes: guides/ignored.md
      - Configuration File: guides/config.md
      - Report Formats: guides/reports.md
