package com.github.maracas.roseau.diff.changes;

import static com.github.maracas.roseau.diff.changes.BreakingChangeNature.ADDITION;
import static com.github.maracas.roseau.diff.changes.BreakingChangeNature.DELETION;
import static com.github.maracas.roseau.diff.changes.BreakingChangeNature.MUTATION;

/**
 * Kinds of breaking changes that can be detected.
 */
public enum BreakingChangeKind {
	TYPE_REMOVED(DELETION),
	CLASS_NOW_ABSTRACT(MUTATION),
	CLASS_NOW_FINAL(MUTATION),
	NESTED_CLASS_NOW_STATIC(MUTATION),
	NESTED_CLASS_NO_LONGER_STATIC(MUTATION),
	CLASS_TYPE_CHANGED(MUTATION),
	CLASS_NOW_CHECKED_EXCEPTION(MUTATION),
	TYPE_NOW_PROTECTED(MUTATION),
	SUPERTYPE_REMOVED(MUTATION),
	TYPE_FORMAL_TYPE_PARAMETERS_ADDED(MUTATION),
	TYPE_FORMAL_TYPE_PARAMETERS_REMOVED(MUTATION),
	TYPE_FORMAL_TYPE_PARAMETERS_CHANGED(MUTATION),

	METHOD_REMOVED(DELETION),
	METHOD_LESS_ACCESSIBLE(MUTATION),
	METHOD_RETURN_TYPE_CHANGED(MUTATION),
	METHOD_NOW_ABSTRACT(MUTATION),
	METHOD_NOW_FINAL(MUTATION),
	METHOD_NOW_STATIC(MUTATION),
	METHOD_NOW_NATIVE(MUTATION),
	METHOD_NOW_VARARGS(MUTATION),
	METHOD_NO_LONGER_VARARGS(MUTATION),
	METHOD_NO_LONGER_STATIC(MUTATION),
	METHOD_NO_LONGER_STRICTFP(MUTATION),
	METHOD_ADDED_TO_INTERFACE(ADDITION),
	METHOD_NOW_THROWS_CHECKED_EXCEPTION(MUTATION),
	METHOD_NO_LONGER_THROWS_CHECKED_EXCEPTION(MUTATION),
	METHOD_ABSTRACT_ADDED_TO_CLASS(ADDITION),
	METHOD_ABSTRACT_NOW_DEFAULT(MUTATION),
	METHOD_FORMAL_TYPE_PARAMETERS_ADDED(MUTATION),
	METHOD_FORMAL_TYPE_PARAMETERS_REMOVED(MUTATION),
	METHOD_FORMAL_TYPE_PARAMETERS_CHANGED(MUTATION),

	FIELD_NOW_FINAL(MUTATION),
	FIELD_NOW_STATIC(MUTATION),
	FIELD_NO_LONGER_STATIC(MUTATION),
	FIELD_TYPE_CHANGED(MUTATION),
	FIELD_REMOVED(DELETION),
	FIELD_LESS_ACCESSIBLE(MUTATION),

	CONSTRUCTOR_REMOVED(DELETION),
	CONSTRUCTOR_LESS_ACCESSIBLE(MUTATION),

	METHOD_PARAMETER_GENERICS_CHANGED(MUTATION);

	// Do not make sense or unsupported or not implemented yet
	/*ANNOTATION_DEPRECATED_ADDED,

	TYPE_GENERICS_CHANGED,

	METHOD_LESS_ACCESSIBLE_THAN_IN_SUPERCLASS,
	METHOD_IS_STATIC_AND_OVERRIDES_NOT_STATIC,
	METHOD_IS_NOT_STATIC_AND_OVERRIDES_STATIC,
	METHOD_RETURN_TYPE_GENERICS_CHANGED,
	METHOD_PARAMETER_GENERICS_CHANGED,
	METHOD_NEW_DEFAULT,
	METHOD_MOVED_TO_SUPERCLASS,

	FIELD_STATIC_AND_OVERRIDES_NON_STATIC,
	FIELD_NON_STATIC_AND_OVERRIDES_STATIC,
	FIELD_LESS_ACCESSIBLE_THAN_IN_SUPERCLASS,
	FIELD_GENERICS_CHANGED,

	CONSTRUCTOR_PARAMS_GENERICS_CHANGED,
	CONSTRUCTOR_GENERICS_CHANGED,
	CONSTRUCTOR_FORMAL_TYPE_PARAMETERS_CHANGED,
	CONSTRUCTOR_FORMAL_TYPE_PARAMETERS_ADDED,
	CONSTRUCTOR_FORMAL_TYPE_PARAMETERS_REMOVED;*/

	private final BreakingChangeNature nature;

	BreakingChangeKind(BreakingChangeNature nature) {
		this.nature = nature;
	}

	public BreakingChangeNature getNature() {
		return nature;
	}
}
