package testing_lib.accessModifierClazzConstructorAccessIncreasePrivateToProtected;

public class AccessModifierClazzConstructorAccessIncreasePrivateToProtected {

    private AccessModifierClazzConstructorAccessIncreasePrivateToProtected() {}

}