package testing_lib.accessModifierClazzConstructorAccessIncreaseProtectedToPublic;

public class AccessModifierClazzConstructorAccessIncreaseProtectedToPublic {

    protected AccessModifierClazzConstructorAccessIncreaseProtectedToPublic() {}

}