name: Maven Build & Test (main)

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Build with Maven
        run: mvn --batch-mode -DskipTests package
      - name: Run tests
        id: tests
        continue-on-error: true
        run: mvn --batch-mode verify
      - name: Build tests report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Maven Tests
          path: '**/target/surefire-reports/*.xml'
          reporter: java-junit
          fail-on-error: true
      - name: Fail if tests failed
        if: steps.tests.outcome == 'failure'
        run: exit 1
      - name: Publish SNAPSHOT
        if: ${{ success() && github.event_name == 'push' }}
        run: mvn --batch-mode -DskipTests -Ppublish-sonatype deploy
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.NEXUS_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
