package com.github.maracas.roseau.changes;

/**
 * Enumerates the source and binary breaking changes taken into account.
 */
public enum BreakingChangeKind {
	ANNOTATION_DEPRECATED_ADDED,
	INTERFACE_REMOVED,
	CLASS_REMOVED,
	CLASS_NOW_ABSTRACT,
	CLASS_NOW_FINAL,
	NESTED_CLASS_NOW_STATIC,
	NESTED_CLASS_NO_LONGER_STATIC,
	CLASS_TYPE_CHANGED,
	CLASS_NOW_CHECKED_EXCEPTION,
	TYPE_LESS_ACCESSIBLE,
	SUPERCLASS_MODIFIED_INCOMPATIBLE,
	TYPE_GENERICS_CHANGED,
	FORMAL_TYPE_PARAMETERS_ADDED,
	FORMAL_TYPE_PARAMETERS_REMOVED,


	METHOD_REMOVED,
	METHOD_LESS_ACCESSIBLE,
	METHOD_LESS_ACCESSIBLE_THAN_IN_SUPERCLASS,
	METHOD_IS_STATIC_AND_OVERRIDES_NOT_STATIC,
	METHOD_IS_NOT_STATIC_AND_OVERRIDES_STATIC,
	METHOD_RETURN_TYPE_CHANGED,
	METHOD_RETURN_TYPE_GENERICS_CHANGED,
	METHOD_PARAMETER_GENERICS_CHANGED,
	METHOD_NOW_ABSTRACT,
	METHOD_NOW_FINAL,
	METHOD_NOW_STATIC,
	METHOD_NOW_NATIVE,
	METHOD_NO_LONGER_STATIC,
	METHOD_NO_LONGER_STRICTFP,
	METHOD_NOW_VARARGS,
	METHOD_NO_LONGER_VARARGS,
	METHOD_ADDED_TO_INTERFACE,
	METHOD_NOW_THROWS_CHECKED_EXCEPTION,
	METHOD_NO_LONGER_THROWS_CHECKED_EXCEPTION,
	METHOD_ABSTRACT_ADDED_TO_CLASS,
	METHOD_NEW_DEFAULT,    // Not taking this into account
	METHOD_MOVED_TO_SUPERCLASS,
	METHOD_ABSTRACT_NOW_DEFAULT,
	METHOD_FORMAL_TYPE_PARAMETERS_ADDED,
	METHOD_FORMAL_TYPE_PARAMETERS_REMOVED,


	FIELD_STATIC_AND_OVERRIDES_NON_STATIC,
	FIELD_NON_STATIC_AND_OVERRIDES_STATIC,
	FIELD_LESS_ACCESSIBLE_THAN_IN_SUPERCLASS,
	FIELD_NOW_FINAL,
	FIELD_NOW_STATIC,
	FIELD_NO_LONGER_STATIC,
	FIELD_TYPE_CHANGED,
	FIELD_REMOVED,
	FIELD_LESS_ACCESSIBLE,
	FIELD_GENERICS_CHANGED,


	CONSTRUCTOR_REMOVED,
	CONSTRUCTOR_LESS_ACCESSIBLE,
	CONSTRUCTOR_PARAMS_GENERICS_CHANGED,
	CONSTRUCTOR_GENERICS_CHANGED,
	CONSTRUCTOR_FORMAL_TYPE_PARAMETERS_ADDED,
	CONSTRUCTOR_FORMAL_TYPE_PARAMETERS_REMOVED



}
