package com.github.maracas.roseau.changes;

public enum BreakingChangeKind {
	CLASS_NOW_ABSTRACT,
	CLASS_NOW_FINAL,
	TYPE_KIND_CHANGED,
	CLASS_NOW_CHECKED_EXCEPTION,
	METHOD_REMOVED,
	METHOD_NOW_STATIC,
	METHOD_NOW_FINAL,
	METHOD_NOW_ABSTRACT,
	CONSTRUCTOR_REMOVED,
	CONSTRUCTOR_NOW_PROTECTED,
	FIELD_REMOVED,
	METHOD_NOW_PROTECTED,
	FIELD_NOW_PROTECTED,
	FIELD_NO_LONGER_STATIC,
	FIELD_NOW_STATIC,
	FIELD_NOW_FINAL,
	TYPE_REMOVED
}
